"""empty message

Revision ID: 352c7df68af2
Revises: c2b304e2d61a
Create Date: 2018-11-03 17:52:26.131443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352c7df68af2'
down_revision = 'c2b304e2d61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'quantity')
    # ### end Alembic commands ###
