"""empty message

Revision ID: b2376d864916
Revises: be7ee13e278c
Create Date: 2018-11-25 16:47:01.308842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2376d864916'
down_revision = 'be7ee13e278c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('foil', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'foil')
    # ### end Alembic commands ###
