"""empty message

Revision ID: b8197dc0f048
Revises: bd96768a8875
Create Date: 2018-11-12 16:13:37.335984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8197dc0f048'
down_revision = 'bd96768a8875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wishlist', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_column('wishlist', 'user_id')
    # ### end Alembic commands ###
