"""empty message

Revision ID: be7ee13e278c
Revises: a3a405991176
Create Date: 2018-11-23 18:34:03.085083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7ee13e278c'
down_revision = 'a3a405991176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expansion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='unique_exp_code')
    )
    op.create_table('cards_to_expansions',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('expansion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['expansion_id'], ['expansion.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'expansion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards_to_expansions')
    op.drop_table('expansion')
    # ### end Alembic commands ###
