"""empty message

Revision ID: e7a8708ca1ad
Revises: b2376d864916
Create Date: 2018-12-02 13:10:38.867279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a8708ca1ad'
down_revision = 'b2376d864916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('min_condition', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'min_condition')
    # ### end Alembic commands ###
